keys:
  - &users
    pgp:
    - &misterio 7088C7421873E0DB97FF17C2245CAB70B4C225E9
  - &hosts
    age:
    - &atlas age1hm5lf4qk84r4wh00atn6hpts7mpdx80adq26wht2e5qh9ewvhyaszfv82d
    - &merope age1709qfrwglm75v5x8lpuhryt83k6p6c90npplzzec6a5w8ct93ejscpqpc3
  - &all
    <<: [*users, *hosts]

creation_rules:
  - path_regex: nixos/hosts/[^/]+/secrets/[^/]+\.ya?ml$
    key_groups:
      - <<: *all
  - path_regex: nixos/common/secrets/[^/]+\.ya?ml$
    key_groups:
      - <<: *all
